apiVersion: v1
kind: Service
metadata:
  name: network-resources-injector-service
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: network-resources-injector
