name: Docker-build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build only
      uses: docker/build-push-action@v2
      with:
        push: false
        context: .
        file: ./Dockerfile
        tags: network-resources-injector:latest
